[build]
  command = "npm run build"
  publish = ".next"
  base = "/"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "https://azzar.netlify.app/*"
  to = "https://glassgallery.my.id/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/id"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/en"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/login"
  to = "/"
  status = 301
  force = true
