[build]
  command = "npm run build"
  publish = ".next"
  base = "/"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/id"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/en"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/login"
  to = "/"
  status = 301
  force = true
